### ISSUE TITLE
D=16 crash

### ISSUE THREAD

**Issue by ktprime** [skarupke/heap#2]
```
template<int D, typename It, typename Compare>
void push_dary_heap(It begin, It end, Compare && compare)
{
    typename std::iterator_traits<It>::value_type value = std::move(end[-1]);
    uint64_t index = (end - begin) - 1;
    while ((int)index > 0)  //fix here
    {
        uint64_t parent = dary_heap_helpers::parent_index<D>(index);
        if (!compare(begin[parent], value))
            break;
        begin[index] = std::move(begin[parent]);
        index = parent;
    }
    begin[index] = std::move(value);
}
```

**Comment by skarupke** [comment]
Do you have a reproduce case for this? I don't see how index can ever go below zero, no matter the value for D. Except if push_dary_heap was called on an empty range, but that would already be invalid due to the first line.

**Comment by ktprime** [comment]
> Do you have a reproduce case for this? I don't see how index can ever go below zero, no matter the value for D. Except if push_dary_heap was called on an empty range, but that would already be invalid due to the first line.

if begin == end it will be crashed, but for std::make_heap it works.

my test code like follow
```
    {
        ts = NowMs(); long mask = 0;
        for (int m = 0; m < k; m++) {
            a[m] = a[m + n];
            push_dary_heap<16>(a, a + m); //crash if m == 0
        }
        printf("\t dary_heap16  %5ld ms, ", NowMs() - ts);
        for (int m = k; m > 0; m--) {
            mask ^= a[0];
            pop_dary_heap<16>(a, a + m);
        }
        printf("pop mask = %ld,  %5ld ms\n", mask, NowMs() - ts);
    }
```

**Comment by skarupke** [comment]
Ah that is incorrect usage. This is the same interface as std::push_heap. So the newly-pushed element has to be at end[-1]. So in your code you have to call push_dary_heap<16>(a, a + m + 1).

Try replacing push_dary_heap with std::push_heap and you'd get the same problem.
